export const PRIV_SELL_WAREHOUSE = "PRIV_SELL_WAREHOUSE";
export const PRIV_BUY_WAREHOUSE = "PRIV_BUY_WAREHOUSE";
export const PRIV_KASSABANK = "PRIV_KASSABANK";
export const PRIV_REPORT = "PRIV_REPORT";
export const PRIV_SETTINGS = "PRIV_SETTINGS";


